pathname = {
  "/" ~
  (country ~ "/") ~
  (service_type ~ "/") ~
  (slug ~ "/") ~
  (data ~ "/")?
}

country = @{ ASCII_ALPHA{2} }

service_type = @{ (ASCII_ALPHA_LOWER | "-"){3,} }

slug = { title? ~ id }

title = @{ (title_part+ ~ "-")+ }
title_part = _{ (ASCII_ALPHANUMERIC | pct_encoded)+ }

id = @{ ASCII_ALPHANUMERIC+ }

data = @{ (ASCII_ALPHANUMERIC | "-" | "_" )+ }

pct_encoded = _{ "%" ~ (ASCII_ALPHA_UPPER | ASCII_DIGIT){2} }
