[package]
name = "karrot-permalink"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
percent-encoding = "2.2"
pest = "2.0"
pest_derive = "2.0"
regex = "1"
thiserror = "1.0"
unicode-normalization = "0.1.22"
url = "2.3"
